### ISSUE TITLE
NoApiKeys Error

### ISSUE THREAD

**Issue by outline4** [TopShelfCraft/Maps#1]
Hi, 
Google Maps has stopped working suddenly and spits out 2 errors: 
Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps JavaScript API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

this is the twig code I use: 

	{% set options = {
		id: 'map_canvas',
		class: 'mapping',
		controls: 'zoom|pan|scale|overview|map_type|rotate|streetview',
		map_type_default: 'normal',
		interact: 'drag|click_zoom|drag_zoom',
		height: '400px',
		}
	%}
	{{ craft.squareBitMaps.map(entry.cf_map, options) }}

this is the output: 

	"": ""
	class: "mapping"
	height: "400px"
	id: "map_canvas"
	key: "THEAPIKEYFROMTHEBACKEND"
	map_click_zoom: "1"
	map_drag: "1"
	map_scroll_zoom: ""
	map_type_default: "normal"
	ui_map_type: "1"
	ui_overview: "1"
	ui_pan: "1"
	ui_rotate: "1"
	ui_scale: "1"
	ui_streetview: "1"
	ui_zoom: "1"
	width: ""

do you know what to check in order to make it work again? 

cheers. 
Stefan

**Comment by michaelrog** [comment]
I suspect this is due to Google's deprecating their v2 API. You can get more info at their guide for [Upgrading Your Maps JavaScript API Application from V2 to V3](https://developers.google.com/maps/documentation/javascript/v2tov3).

I don't have plans at the moment to push further updates on Maps for Craft 2; [Smart Map](https://github.com/doublesecretagency/craft-smartmap) is a great replacement.
